service: posts-service

plugins:
  - serverless-bundle

custom:
  resources:
    kinesisStreamArn: ${ssm:/ms_demo/kinesis_stream/arn}

provider:
  lambdaHashingVersion: 20201221
  name: aws
  runtime: nodejs14.x
  region: us-east-1
  memorySize: 256
  stage: ${opt:stage, 'v1'}
  environment:
    DB_URL: ${ssm:/ms_demo/posts/db_url}
    DB_NAME: posts
    KINESIS_STREAM_NAME: ${ssm:/ms_demo/kinesis_stream/name}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - kinesis:PutRecord
        - kinesis:PutRecords
      Resource: ${self:custom.resources.kinesisStreamArn}

functions:
  hello:
    handler: src/handlers/hello.handler
    events:
      - http:
          method: GET
          path: /hello

  createPost:
    handler: src/handlers/createPost.handler
    events:
      - http:
          method: POST
          path: /posts

  eventConsumer:
    handler:  src/handlers/eventConsumer.handler
    events:
      - stream:
          type: kinesis
          arn: ${self:custom.resources.kinesisStreamArn}
