service: posts-service

plugins:
  - serverless-bundle

provider:
  lambdaHashingVersion: 20201221
  name: aws
  runtime: nodejs14.x
  region: us-east-1
  memorySize: 256
  stage: ${opt:stage, 'v1'}
  environment:
    DB_URL: ${ssm:/ms_demo/posts/db_url}
    DB_NAME: posts

functions:
  hello:
    handler: src/handlers/hello.handler
    events:
      - http:
          method: GET
          path: /hello

  createPost:
    handler: src/handlers/createPost.handler
    events:
      - http:
          method: POST
          path: /posts
